language: python
matrix:
  include:
  - os: linux
    python: '2.7'
    language: generic
    dist: xenial
  - os: linux
    python: '3.6'
    language: generic
    dist: xenial
install:
  - pip install -r requirements.txt --user
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    pip install m2crypto --user;
    sudo apt-get install -y usbmuxd;
    fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    python test/__init__.py;
    fi
before_deploy: 
  - echo $TRAVIS_TAG > version.txt
  - export PATH=/Users/travis/Library/Python/2.7/bin:$PATH
deploy:
  skip_cleanup: true
  skip_existing: true
  provider: pypi
  user: qta
  password: 
    secure: tzAoq5UnwaqQGHcH4qSnN0hfFop7f/Gjgf3DTWrblpn+vBIOBk4umJIAAF2u5tUHuhxm14UmDEuDciQM9j6DEoy+7VPhe8KY8cVhBjIYpEIBjYr4WeRsl2rhDPlYnp5wDHdsY4bsJgtOSjVCbdKZ9VhV0cjUegKU3oEX5k1qu/XPDNbiZhWs/zjyXwKAbnTBqcJlcdZphVeEgC9E8DMCQRRTfNXtqSmZj8EkjSwlbIAldZflqX7/Xg7/pFPaKjwQW1BvIaPUqvvwQLGvyqr4zovF4SQ8UpUPHMuhYY/0jJijgRe0VkI9SsCXbWFmMZrgkyfvjOmGLc3dYaaINh1jf6zoVWddtgeRW9mNs0GzcPz9PefefeNgIQ9yyM99Uv0nqrAdARO87SrtGCQ4CNrAOwaXJElzKcTJOfpbrLedbnqczzC5wa5LZYsMZudiULpiPOEK6MZ4spOnt8D2/8tSIOQMfY3BF5vUXYBEM+uuj38lKfZGXT2Ox9XzMZZPjkV5F5ky73oAdMEPTBJWUAI2xXeESBMSfh7NP0019kTloKOpDsgFknGQdLfGWdcONWmJWP1yreavcz9fLEWJXz+mdTzUcVKg2JLouUmhAdKtlU9oS6n9R3T0OZ0QlltLqnkp+IC0KouaTLrIBZ16IoYjnxJ3/pc/+FN8lV3nY/XFsnY=
  distributions: "sdist"
  on:
    tags: true
    branch: master
    condition: $TRAVIS_TAG =~ [0-9]+\.[0-9]+\.[0-9]+
